use_frameworks!

platform :ios, '11.0'

target 'TYHTestUtils_Example' do
  pod 'TYHTestUtils', :path => '../'
  
  target 'TYHTestUtils_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end
